services:
  # API GATEWAY (punto de entrada)
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${GATEWAY_PORT}:80"
    depends_on:
      - ut5-api

  # API DE UT5API
  ut5-api:
    build: ./UT5API
    container_name: ut5-api
    ports:
      - "${UT5_API_PORT}:8080"
    env_file:
      - ./UT5API/.env
    depends_on:
      - ut5-db

  ut5-db:
    image: mysql:8.0
    container_name: ut5-db
    env_file:
      - ./UT5API/.env
    volumes:
      - ut5-db-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  ut5-db-data:


